import json
import re
from typing import Any

from .models import Artifact, Target
from .schema import Operation


def _sample_value(parameter: dict[str, Any]) -> Any:
    schema = parameter.get("schema", {})
    if "example" in parameter:
        return parameter["example"]
    if "example" in schema:
        return schema["example"]
    if "default" in schema:
        return schema["default"]
    if schema.get("enum"):
        return schema["enum"][0]
    return {"integer": 1, "number": 1.0, "boolean": True}.get(schema.get("type"), "test")


def _render_path(operation: Operation) -> str:
    result = operation.path
    for parameter in operation.parameters:
        if parameter.get("in") == "path" and isinstance(parameter.get("name"), str):
            result = result.replace("{" + parameter["name"] + "}", str(_sample_value(parameter)))
    return re.sub(r"\{[^{}]+\}", "test", result)


def _query(operation: Operation) -> dict[str, str]:
    return {
        str(p["name"]): str(_sample_value(p))
        for p in operation.parameters
        if p.get("in") == "query" and p.get("required") and p.get("name")
    }


def postman_artifact(operations: list[Operation], base_url: str) -> Artifact:
    items = []
    for op in operations:
        query = [{"key": k, "value": v} for k, v in _query(op).items()]
        test = f"pm.test('contract status', () => pm.expect(pm.response.code).to.eql({op.success_status}));"
        items.append({
            "name": op.operation_id,
            "request": {
                "method": op.method,
                "header": [{"key": "Authorization", "value": "Bearer {{apiToken}}", "type": "text"}] if op.has_auth else [],
                "url": {"raw": "{{baseUrl}}" + _render_path(op), "host": ["{{baseUrl}}"], "path": [p for p in _render_path(op).split("/") if p], "query": query},
            },
            "event": [{"listen": "test", "script": {"type": "text/javascript", "exec": [test]}}],
        })
    collection = {
        "info": {"name": "SpecSentinel contract pack", "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},
        "variable": [{"key": "baseUrl", "value": base_url}, {"key": "apiToken", "value": ""}],
        "item": items,
    }
    return Artifact(filename="postman/specsentinel.collection.json", media_type="application/json", content=json.dumps(collection, indent=2))


def pytest_artifact(operations: list[Operation], base_url: str) -> Artifact:
    cases = [(op.method, _render_path(op), op.success_status, _query(op), op.has_auth) for op in operations]
    code = f'''"""Generated by SpecSentinel. Set API_BASE_URL and API_TOKEN at runtime."""
import os
import pytest
import httpx

BASE_URL = os.getenv("API_BASE_URL", {base_url!r}).rstrip("/")
CASES = {cases!r}

@pytest.mark.parametrize("method,path,status,params,needs_auth", CASES)
def test_api_contract(method, path, status, params, needs_auth):
    headers = {{}}
    if needs_auth:
        token = os.getenv("API_TOKEN")
        if not token:
            pytest.skip("API_TOKEN is required for this operation")
        headers["Authorization"] = f"Bearer {{token}}"
    with httpx.Client(timeout=15.0, follow_redirects=False) as client:
        response = client.request(method, BASE_URL + path, params=params, headers=headers)
    assert response.status_code == status, response.text[:1000]

@pytest.mark.parametrize("method,path,_status,params,needs_auth", CASES)
def test_missing_auth_is_rejected(method, path, _status, params, needs_auth):
    if not needs_auth:
        pytest.skip("operation is public")
    with httpx.Client(timeout=15.0, follow_redirects=False) as client:
        response = client.request(method, BASE_URL + path, params=params)
    assert response.status_code in (401, 403), response.text[:1000]
'''
    return Artifact(filename="pytest/test_specsentinel_contract.py", media_type="text/x-python", content=code)


def playwright_artifact(operations: list[Operation], base_url: str) -> Artifact:
    cases = [{"method": op.method, "path": _render_path(op), "status": op.success_status, "query": _query(op), "auth": op.has_auth} for op in operations]
    code = f'''import {{ test, expect }} from '@playwright/test';

const baseURL = (process.env.API_BASE_URL ?? {json.dumps(base_url)}).replace(/\\/$/, '');
const cases = {json.dumps(cases, indent=2)} as const;

for (const c of cases) {{
  test(`${{c.method}} ${{c.path}} satisfies its contract`, async ({{ request }}) => {{
    const headers: Record<string, string> = {{}};
    if (c.auth) {{
      test.skip(!process.env.API_TOKEN, 'API_TOKEN is required for this operation');
      headers.Authorization = `Bearer ${{process.env.API_TOKEN}}`;
    }}
    const response = await request.fetch(baseURL + c.path, {{
      method: c.method, params: c.query, headers, timeout: 15_000, maxRedirects: 0,
    }});
    expect(response.status(), (await response.text()).slice(0, 1000)).toBe(c.status);
  }});
}}
'''
    return Artifact(filename="playwright/specsentinel.spec.ts", media_type="text/typescript", content=code)


def generate_artifacts(targets: list[Target], operations: list[Operation], base_url: str) -> list[Artifact]:
    factories = {Target.POSTMAN: postman_artifact, Target.PYTEST: pytest_artifact, Target.PLAYWRIGHT: playwright_artifact}
    return [factories[target](operations, base_url) for target in targets]
